apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: laravel
        - name: MYSQL_PASSWORD
          value: laravel
        - name: MYSQL_ROOT_PASSWORD
          value: laravel
        - name: MYSQL_USER
          value: chofifa
        image: mysql:5.7
        imagePullPolicy: ""
        name: mysql
        ports:
        - containerPort: 3306
        resources: {}
#        volumeMounts:
#        - mountPath: /var/lib/mysql
#          name: mysql
      restartPolicy: Always
#      volumes:
#      - name: mysql
#        persistentVolumeClaim:
#          claimName: mysql
#status: {}
